{
 "title": "Lab",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Router",
    "query": "SHOW TAG VALUES ON \"telemetry\" FROM \"ELK-Lab\" WITH KEY = \"hostname\""
   },
   {
    "name": "port",
    "label": "Fisical port",
    "query": "SHOW TAG VALUES ON \"telemetry\" FROM \"interface\" WITH KEY = \"ifDescr\" WHERE \"hostname\" = '${hostname}'"
   },
   {
    "name": "source",
    "query": "SHOW TAG VALUES ON \"telemetry\" FROM \"interface\" WITH KEY = \"source\" WHERE \"hostname\" = '${hostname}'"
   },
   {
    "name": "lport",
    "label": "Logical port",
    "query": "SHOW TAG VALUES ON \"telemetry\" FROM \"netflow\" WITH KEY = \"src_port\" WHERE \"source\" =~ /^${source}$/"
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  { "title": "Router", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Top Ports Download",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "ifDescr::tag" ], "type": "tag" }
     ],
     "measurement": "interface",
     "select": [
      [
       { "params": [ "ifInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "hostname::tag", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "ifDescr::tag", "operator": "=~", "value": "/^$port$/" }
     ]
    }
   ]
  },
  {
   "title": "${hostname} Portas ${port} ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "ifDescr::tag" ], "type": "tag" }
     ],
     "measurement": "interface",
     "select": [
      [
       { "params": [ "ifInOctets" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "hostname::tag", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "ifDescr::tag", "operator": "=~", "value": "/^$port$/" }
     ]
    }
   ]
  },
  { "title": "Flow", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Top Src Host",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "SELECT \"src\", TOP(\"sum\", 5)\nFROM (\n    SELECT SUM(\"in_bytes\") AS \"sum\"\n    FROM \"telemetry\".\"autogen\".\"netflow\"\n    WHERE \"source\" =~ /^$source$/ \n    AND \"src_port\" =~ /^$lport$/\n    GROUP BY \"src\"\n)"
    }
   ]
  },
  {
   "title": "Top Dst Host",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"dst\", TOP(\"sum\", 5)\nFROM (\n    SELECT SUM(\"in_bytes\") AS \"sum\"\n    FROM \"telemetry\".\"autogen\".\"netflow\"\n    WHERE \"source\" =~ /^$source$/ \n    AND \"src_port\" =~ /^$lport$/\n    GROUP BY \"dst\"\n)"
    }
   ]
  },
  {
   "title": "Trafic ${hostname} Logical Port ${lport}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "repeat": "lport",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "src::tag" ], "type": "tag" },
      { "params": [ "dst::tag" ], "type": "tag" }
     ],
     "measurement": "netflow",
     "query": "SELECT \"in_bytes\" FROM \"netflow\" WHERE (\"source\"::tag =~ /^$source$/) AND $timeFilter GROUP BY \"src\"::tag, \"dst\"::tag",
     "select": [
      [
       { "params": [ "in_bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source::tag", "operator": "=~", "value": "/^$source$/" },
      { "condition": "AND", "key": "src_port::tag", "operator": "=~", "value": "/^$lport$/" }
     ]
    }
   ]
  }
 ]
}