{
 "title": "Netflow Exporter Overview",
 "description": "Show a Summary from Netflow Exporter Devices",
 "tags": [
  "netflow",
  "nfcollector",
  "exporter",
  "overview"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Interval",
    "label": "Group By Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "Host",
    "label": "Host",
    "query": "SHOW TAG VALUES ON \"telemetry\" FROM \"netflow\" WITH KEY = \"source\""
   },
   {
    "name": "ProtoName",
    "label": "Protocol",
    "query": "SHOW TAG VALUES ON \"telemetry\" FROM \"netflow\" WITH KEY = \"src_port\" WHERE \"source\" =~ /^${Host}$/"
   },
   { "name": "TopVal", "label": "Top", "query": "5,10,20,50" }
  ]
 },
 "panels": [
  {
   "title": "NetFlow Exporter: $Host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "nfExporter",
   "targets": [
    {}
   ]
  },
  {
   "title": "Port $ProtoName",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "repeat": "ProtoName",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "src::tag" ], "type": "tag" },
      { "params": [ "dst::tag" ], "type": "tag" }
     ],
     "measurement": "netflow",
     "select": [
      [
       { "params": [ "in_bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Protocol Usage",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 6 },
   "format": "decbytes",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_ProtoName",
     "groupBy": [
      { "params": [ "ProtoName" ], "type": "tag" },
      { "params": [ "ExpHost" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sum_proto",
     "query": "SELECT sum(\"Bytes\") FROM \"sum_proto\" WHERE (\"ExpHost\" =~ /^$nfExporter$/ AND \"ProtoName\" =~ /^$ProtoName$/) AND $timeFilter GROUP BY \"ProtoName\" fill(null)",
     "select": [
      [
       { "params": [ "Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "ExpHost", "operator": "=~", "value": "/^$nfExporter$/" },
      { "condition": "AND", "key": "ProtoName", "operator": "=~", "value": "/^$ProtoName$/" }
     ]
    }
   ]
  },
  {
   "title": "Top Src Host",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "query": "SELECT \"src\", TOP(\"sum\", $TopVal)\nFROM (\n    SELECT SUM(\"in_bytes\") AS \"sum\"\n    FROM \"telemetry\".\"autogen\".\"netflow\"\n    WHERE \"source\" =~ /^$Host$/ \n    AND \"src_port\" =~ /^$ProtoName$/\n    GROUP BY \"src\"\n)"
    }
   ]
  },
  {
   "title": "Top Dst Host",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"dst\", TOP(\"sum\", $TopVal)\nFROM (\n    SELECT SUM(\"in_bytes\") AS \"sum\"\n    FROM \"telemetry\".\"autogen\".\"netflow\"\n    WHERE \"source\" =~ /^$Host$/ \n    AND \"src_port\" =~ /^$ProtoName$/\n    GROUP BY \"dst\"\n)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top Src Port",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"src_port\", TOP(\"sum\", $TopVal)\nFROM (\n    SELECT SUM(\"in_bytes\") AS \"sum\"\n    FROM \"telemetry\".\"autogen\".\"netflow\"\n    WHERE \"source\" =~ /^$Host$/ \n    AND \"src_port\" =~ /^$ProtoName$/\n    GROUP BY \"src_port\"\n)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top Dst Port",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT dPort,TOP(\"sum\", $TopVal) FROM (SELECT SUM(Bytes) AS \"sum\"  FROM sum_proto WHERE (\"ExpHost\" =~ /^$nfExporter$/ AND \"ProtoName\" =~ /^$ProtoName$/) AND $timeFilter GROUP BY dPort)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top Src Country (City)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 18 },
   "format": "bytes",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_sCouLo ($tag_sCit)",
     "groupBy": [
      { "params": [ "sCouLo" ], "type": "tag" },
      { "params": [ "sCit" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sum_proto_geo",
     "select": [
      [
       { "params": [ "Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "ExpHost", "operator": "=~", "value": "/^$nfExporter$/" },
      { "condition": "AND", "key": "sCouLo", "operator": "=~", "value": "/.*/" },
      { "condition": "AND", "key": "sCit", "operator": "=~", "value": "/.*/" },
      { "condition": "AND", "key": "ProtoName", "operator": "=~", "value": "/^$ProtoName$/" }
     ]
    }
   ]
  },
  {
   "title": "Top Dst Country (City)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 18 },
   "format": "bytes",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_dCouLo ($tag_dCit)",
     "groupBy": [
      { "params": [ "dCouLo" ], "type": "tag" },
      { "params": [ "dCit" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sum_proto_geo",
     "select": [
      [
       { "params": [ "Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "ExpHost", "operator": "=~", "value": "/^$nfExporter$/" },
      { "condition": "AND", "key": "dCouLo", "operator": "=~", "value": "/.*/" },
      { "condition": "AND", "key": "dCit", "operator": "=~", "value": "/.*/" },
      { "condition": "AND", "key": "ProtoName", "operator": "=~", "value": "/^$ProtoName$/" }
     ]
    }
   ]
  }
 ]
}